// <auto-generated />
namespace Cyber_Employee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addIDToRate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addIDToRate));
        
        string IMigrationMetadata.Id
        {
            get { return "201810262213350_addIDToRate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
